
title: Abdul Sayed | Professional Portfolio

url: "https://abdul-sayed.github.io" 

baseurl: ""

bio-page-label: Resume

theme-home: theme-home-builtin-1.html
theme-projects: theme-projects-builtin-1.html
theme-essays: theme-essays-builtin-1.html
theme-bio: theme-bio-builtin-1.html

# Specify the rouge syntax highlighter theme. Pick one from css/rouge.
rouge-theme: igorpro


markdown: kramdown
include: [_data]

